---
achievements:
  achievements:
    survived_pf1:
      type: community
      message: I Survived PF1: Ported over from Pathfinder 1E.
    that_escalated_quickly:
      type: story
      message: That Escalated Quickly: Survived getting chased out of Alexandria.
  shortcuts:
    achievements: achievement
  types:
    community: fa-users
    portal: fa-globe
    fs3: fa-cubes
    story: fa-book
  permissions:
    manage_achievements: Award and remove achievements.
