---
demographics:
  census_fields:
  - field: name
    width: 18
    title: Name
  - field: ancestry
    width: 13
    title: Ancestry
  - field: heritage
    width: 16
    title: Heritage
  - field: charclass
    width: 13
    title: Class
  demographics:
  - full name
  - gender
  - hair
  - eyes
  - skin
  - height
  - physique
  - played by
  - birthdate
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - gender
  - hair
  - physique
  genders:
    Male:
      possessive_pronoun: his
      subjective_pronoun: he
      objective_pronoun: him
      noun: man
    Female:
      possessive_pronoun: her
      subjective_pronoun: she
      objective_pronoun: her
      noun: woman
    Other:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: person
    Robot:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: robot
  groups:
    Faction:
      desc: Religious or secular affiliation.
      wiki: ''
  help_text:
    played by: "%xcplayedby <actor>%xn - Your 'dream casting' for your character."
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <mm/dd/yyy>%xn or %xcage <years>%xn"
    full name: "%xcfullname <name>%xn - Your character's full name."
  max_age: 500
  min_age: 10
  nickname_field: ''
  nickname_format: "%{name} (%{nickname})"
  permissions:
    manage_demographics: Edit demographics on other players.
  private_properties: []
  required_properties:
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  shortcuts:
    groups: group
    demographics: demographic
    birthday: birthdate
    actors: census played by
    actor: demographic/set played by=
    fullname: demographic/set full name=
    playedby: demographic/set played by=
