---
ictime:
  day_names:
  - Navosday
  - Coyotesday
  - Titansday
  - Sunsday
  - Telmensday
  - Moonsday
  - Bowmansday
  day_offset: 0
  game_start_date: ''
  hour_offset: 0
  month_names:
  - Darkfeast
  - Balefire
  - Shadowfall
  - Starmask
  - Paramount
  - Highsun
  - Skydance
  - Firestide
  - Revel
  - Highhunt
  - Gathering
  - Yule
  time_ratio: 1
  year_offset: -998
