---
ictime:
  day_names:
  - Eliday
  - Variday
  - Tariday
  - Gilday
  - Korday
  - Kesenday
  - Ceriday
  day_offset: 0
  game_start_date: ''
  hour_offset: 0
  month_names:
  - Vhast
  - Pryntar
  - Eatonis
  - Bernfleur
  - Hattanan
  - Firetide
  - Aestry
  - Callem
  - Daeshen
  - Rhaltaas
  - Quintoos
  - Khael
  time_ratio: 1
  year_offset: -998
