---
names:
  restricted:
  - me
  - here
  - Althea
  - Angoron
  - Ceinara
  - Caracoroth
  - Daeus
  - Dana
  - Deimos
  - Eluna
  - Gilead
  - Gunakhar
  - Illotha
  - Kor
  - Maugrim
  - Navos
  - Rada
  - Reos
  - Serriel
  - Taara
  - Tarien
  - Thul
  - Vardama
