---
pf2_ammunition:
  Arrows:
    amount: 10
    bulk: 0.1
    descr: These projectiles are the ammunition for bows. The shaft of an arrow is made
      of wood. It is stabilized in flight by fletching at one end and bears a metal
      head on the other.
    price: 10
    source:
      abbr: CRB
      page_start: 282
      page_stop: 282
  Blowgun Darts:
    amount: 10
    bulk: 0.1
    descr: These thin, light darts are typically made of hardwood and stabilized with
      fletching of down or fur. They are often hollow so they can be used to deliver
      poison.
    name: Blowgun Darts
    price: 5
    source:
      abbr: CRB
      page_start: 281
      page_stop: 281
  Bolts:
    amount: 10
    bulk: 0.1
    descr: Shorter than traditional arrows but similar in construction, bolts are the
      ammunition used by crossbows.
    name: Bolts
    price: 10
    source:
      abbr: CRB
      page_start: 281
      page_stop: 281
  Sling Bullets:
    amount: 10
    bulk: 0.1
    descr: These are small metal balls, typically either iron or lead, designed to be
      used as ammunition in slings.
    name: Sling Bullets
    price: 1
    source:
      abbr: CRB
      page_start: 281
      page_stop: 281
