---
pf2e_rewards:
  prp_reward_types:
    standard_player: prp_reward_normal
    standard_runner: prp_reward_bonus30
    dc_player: prp_reward_bonus30
    dc_runner: prp_reward_bonus60
  prp_reward_normal:
    1:
      xp: 30
      money: 1800
    2: 
      xp: 30
      money: 3000
    3: 
      xp: 30
      money: 5000
    4: 
      xp: 30
      money: 8500
    5: 
      xp: 30
      money: 13500
    6: 
      xp: 30
      money: 20000
    7: 
      xp: 30
      money: 29000
    8: 
      xp: 30
      money: 40000
    9: 
      xp: 30
      money: 57000
    10: 
      xp: 30
      money: 80000
    11: 
      xp: 30
      money: 115000
    12: 
      xp: 30
      money: 165000
    13: 
      xp: 30
      money: 250000
    14: 
      xp: 30
      money: 40000  
    15:
      xp: 30
      money: 545000
    16:
      xp: 30
      money: 825000
    17:
      xp: 30
      money: 1280000
    18:
      xp: 30
      money: 2080000
    19:
      xp: 30
      money: 3550000
    20: 
      xp: 30
      money: 4900000
  prp_reward_bonus30:
    1:
      xp: 40
      money: 2340
    2:
      xp: 40
      money: 3900
    3:
      xp: 40
      money: 6500
    4:
      xp: 40
      money: 11050
    5:
      xp: 40
      money: 17550
    6:
      xp: 40
      money: 26000
    7:
      xp: 40
      money: 37700
    8:
      xp: 40
      money: 52000
    9:
      xp: 40
      money: 74100
    10:
      xp: 40
      money: 104000
    11:
      xp: 40
      money: 149500
    12:
      xp: 40
      money: 214500
    13:
      xp: 40
      money: 325000
    14:
      xp: 40
      money: 474500
    15:
      xp: 40
      money: 708500
    16:
      xp: 40
      money: 1072500
    17:
      xp: 40
      money: 1664000
    18:
      xp: 40
      money: 2704000
    19:
      xp: 40
      money: 4615000
    20:
      xp: 40
      money: 6370000
  prp_reward_bonus60:
    1:
      xp: 50
      money: 2988
    2: 
      xp: 50
      money: 4980
    3:
      xp: 50
      money: 8300
    4: 
      xp: 50
      money: 14110
    5:
      xp: 50
      money: 22410
    6:
      xp: 50
      money: 33200
    7:
      xp: 50
      money: 48140
    8: 
      xp: 50
      money: 66400
    9:
      xp: 50
      money: 94620
    10:
      xp: 50
      money: 132800
    11:
      xp: 50
      money: 190900
    12: 
      xp: 50
      money: 273900
    13: 
      xp: 50
      money: 415000
    14: 
      xp: 50
      money: 605900
    15: 
      xp: 50
      money: 904700
    16: 
      xp: 50
      money: 1369500
    17: 
      xp: 50
      money: 2124800
    18:
      xp: 50
      money: 3452800
    19: 
      xp: 50
      money: 5893000
    20: 
      xp: 50
      money: 8134000
      