---
pf2e:
  allowed_alignments:
  - LG
  - NG
  - CG
  - LN
  - N
  - CN
  condition_colors:
    Dying: "%xr"
    Wounded: "%xy"
  faiths: 
  list_item: "%x43"
  open_npc_sheets: false
  open_sheets: true
  shortcuts:
    sheet/top: sheet/info
  skills:
    Acrobatics:
      key_abil: Dexterity
    Arcana:
      key_abil: Intelligence
    Athletics:
      key_abil: Strength
    Crafting:
      key_abil: Intelligence
    Deception:
      key_abil: Charisma
    Diplomacy:
      key_abil: Charisma
    Intimidation:
      key_abil: Charisma
    Medicine:
      key_abil: Wisdom
    Nature:
      key_abil: Wisdom
    Occultism:
      key_abil: Intelligence
    Performance:
      key_abil: Charisma
    Religion:
      key_abil: Wisdom
    Society:
      key_abil: Intelligence
    Stealth:
      key_abil: Dexterity
    Survival:
      key_abil: Wisdom
    Thievery:
      key_abil: Dexterity
  subclass_names:
    Alchemist: Research Field
    Barbarian: Instinct
    Bard: Muse
    Champion: Cause
    Druid: Order
    Ranger: Hunter's Edge
    Rogue: Racket
    Sorcerer: Bloodline
    Wizard: School
    Investigator: Methodology
    Oracle: Mystery
    Witch: Patron
  title_color: "%x172"
  use_alignment: true
  use_encumbrance: false
