---
pf2e_heritage:
  Aasimar:
    traits:
    - aasimar
    special:
    - Low-Light Vision
    change_vision: true
  Ancient-Blooded:
    reaction: 'Call On Ancient Blood'
  Anvil:
    skills:
    - Crafting
    feats:
    - Specialty Crafting
    - Specialty Crafting
  Arctic:
    defense:
      resistances:
        cold: 1
    circumstance: true
  Ashen One:
    traits:
    - Ashen One
    special:
    - Low-Light Vision
    change_vision: true
  Badlands:
    special:
    - Badlands Oruch
  Cavern:
    special:
    - Darkvision
  Chameleon:
    circumstance: true
  Changeling:
    traits:
    - changeling
    special:
    - Low-Light Vision
    change_vision: true
  Charhide:
    defense:
      resistances:
        fire: 1
    special:
    - Charhide Goblin
  Cliffscale:
    feat:
    - Combat Climber
    special:
    - Cliffscale Lizardfolk
  Dar:
    traits:
    - Dar
    special:
    - Low-Light Vision
    - Negative Healing
    change_vision: true
  Death Warden:
    circumstance: true
  Deep:
    feat:
    - Terrain Expertise/Underground
    - Combat Climber
  Desert:
    defense:
      resistances:
        fire: 1
  Elemental Heart:
    action:
    - Energy Emanation
  Elfbane:
    reaction:
    - Resist Elf Magic
  Fey-Touched:
    traits:
    - fey
    cantrip:
    - [ 'primal' ]
  Forge:
    defense:
      resistances:
        fire: 1
  Frilled:
    special:
    - Frilled Lizardfolk
    action:
    - Threatening Approach
  Gutsy:
    special:
    - Gutsy Lucht
  Half-Sil:
    traits:
    - half-sil
    - sildanyar
    special:
    - Low-Light Vision
  Half-Oruch:
    traits:
    - oruch
    - half-oruch
    special:
    - Low-Light Vision
  Hillock:
    rest_HP_bonus: true
    special:
    - Hillock Lucht
  Hold-Scarred:
    ancestry_HP: 12
    feat:
    - Diehard
  Irongut:
    special:
    - Irongut Goblin
    circumstance: true
  Jinxed-egalrin:
    special:
    - Jinxed Egalrin
  Jinxed-lucht:
    action:
    - Jinx
  Mountainkeeper:
    innate_spell:
      spell_trad: primal
      cantrip:
      - disrupt undead
    special:
    - Mountainkeeper Egalrin
  Nomadic:
    language:
    - language
    - language
  Oathkeeper:
    circumstance: true
  Observant:
    circumstance: true
  Rainfall:
    circumstance: true
  Razortooth:
    attack:
      Jaws:
        damage: 1d6
        damage_type: P
        traits:
        - finesse
        - unarmed
  Rock:
    circumstance: true
  Runtboss:
    feat:
    - Group Coercion
    special:
    - Runtboss Arvek
  Sandstrider:
    defense:
      resistances:
        fire: 1
    special:
    - Sandstrider Lizardfolk
  Seer:
    spell:
      name: 'Detect Magic'
      per_day: false
    action:
    - Identify Magic
    - Decipher Writing
    action_bonus: 1
  Sensate:
    special:
    - Sensate Gnome
    circumstance: true
  Shortshanks:
    feat:
    - Ride
    special:
    - Shortshanks Arvek
  Makari:
    movement:
      Swim: 15
  Skilled:
    skill:
    - [ 'skill' ]
  Skyborn:
    special:
    - Skyborn Egalrin
  Smokeworker:
    defense:
      resistances:
        fire: 1
    special:
    - Smokeworker Arvek
  Snow:
    defense:
      resistances:
        cold: 1
  Steelskin:
    special:
    - Steelskin Arvek
  Stormtossed:
    defense:
      resistances:
        electricity: 1
    special:
    - Stormtossed Egalrin
  Strong-Blooded:
    defense:
      resistances:
        poison: 1
    circumstance: true
  Tailed:
    feat:
    - Combat Climber
    circumstance: true
  Taloned:
    attack:
      Talons:
        damage: 1d4
        damage_type: S
        traits:
        - agile
        - finesse
        - unarmed
        - versatile_P
  Tiefling:
    traits:
    - tiefling
    special:
    - Low-Light Vision
    change_vision: true
  Treedweller:
    circumstance: true
  Twilight:
    special:
    - Low-Light Vision
  Umbral:
    special:
    - darkvision
  Unbreakable:
    ancestry_HP: 10
    special:
    - Unbreakable Goblin
  Unseen:
    circumstance: true
  Versatile:
    feat:
    - [ 'general' ]
  Vivacious:
    defense:
      resistances:
        negative: 1
  Wellspring:
    cantrip:
      - [ 'arcane', 'divine', 'occult' ]
    change_spell_trad: true
  Whisper:
    circumstance: true
  Wildwood:
    special:
    - Wildwood Lucht
  Wintertouched:
    defense:
      resistance:
        cold: 1
  Woodland:
    circumstance: true