pf2e_conditions:
  Blinded:
    short_descr: You're unable to see.
    value: false
    override: "Dazzled"
    modifies:
      - domain: perception
        type: status
        value: "-4"
  Clumsy:
    short_descr: Your movements become clumsy and inexact.
    value: true
    override: false
    modifies:
      - domain: dex-based
        type: status
        value: "-@source.value"
  Confused:
    short_descr: You lose your wits and attack wildly.
    value: false
    override: false
  Controlled:
    short_descr: You are no longer in control of your own actions.
    value: false
    override: false
  Dazzled:
    short_descr: Your eyes are overstimulated and you cannot see clearly.
    value: false
    override: false
  Deafened:
    short_descr: You cannot hear.
    value: false
    override: false
    modifies:
      - domain: perception
        type: status
        value: "-2"
  Doomed:
    short_descr: A powerful force is pulling you towards death.
    value: true
    override: false
    daily: -1
  Drained:
    short_descr: You have lost some of your blood or life force.
    value: true
    override: false
    daily: -1
    modifies:
      - domain: con-based
        type: status
        value: "-@source.value"
      - domain: hp
        type: status
        value: "-@source.value * @actor.level"
  Dying:
    short_descr: You are close to death.
    value: true
    override: false
  Encumbered:
    short_descr: You are carrying too much.
    value: false
    override: false
    modifies:
      - domain: speed
        type: status
        value: "-10"
  Enfeebled:
    short_descr: You are physically weakened.
    value: true
    override: false
    modifies:
      - domain: str-based
        type: status
        value: "-@source.value"
  Fascinated:
    short_descr: You are compelled to focus your attention on something.
    value: false
    override: false
    modifies:
      - domain:
          - perception
          - skill-check
        type: status
        value: "-2"
  Fatigued:
    short_descr: You are tired and cannot summon much energy.
    value: false
    override: false
    daily: false
    modifies:
      - domain:
          - ac
          - saving-throw
        type: status
        value: "-1"
  Fleeing:
    short_descr: You can take no action other than running away.
    value: false
    override: false
  Frightened:
    short_descr: You are gripped by fear.
    value: true
    override: false
    modifies:
      - domain: all
        type: status
        value: "-@source.value"
  Grabbed:
    short_descr: You are being held by another creature.
    value: false
    override: false
  Immobilized:
    short_descr: You are unable to move.
    value: false
    override: false
  Invisible:
    short_descr: You cannot be seen.
    value: false
    override: false
  Off-Guard:
    short_descr: You are caught off-guard or otherwise unable to fully defend yourself.
    value: false
    override: false
    modifies:
      - domain: ac
        type: circumstance
        value: "-2"
  Paralyzed:
    short_descr: You are frozen in place.
  Persistent:
    short_descr: You are taking damage over time from a source.
    value: true
    override: false
  Petrified:
    short_descr: You have been turned to stone.
    value: false
    override: false
  Prone:
    short_descr: You are lying on the ground.
    value: false
    override: false
    modifies:
      - domain: attack-roll
        type: circumstance
        value: "-2"
  Quickened:
    short_descr: You move faster than normal.
    value: false
    override: false
  Restrained:
    short_descr: You are tied up and can barely move.
    value: false
    override: "Grabbed"
  Sickened:
    short_descr: You feel ill.
    value: true
    override: false
    modifies:
      - domain: all
        type: status
        value: "-@source.value"
  Slowed:
    short_descr: You move more slowly than normal.
    value: true
    override: false
  Stunned:
    short_descr: You are reeling and unable to use your senses.
    value: true
    override: "Slowed"
  Stupefied:
    short_descr: Your thoughts are cloudy and indistinct.
    value: true
    override: false
    modifies:
      - domain:
          - int-based
          - wis-based
          - cha-based
        type: status
        value: "-@source.value"
  Unconscious:
    short_descr: You are sleeping or knocked out.
    value: false
    override: false
    modifies:
      - domain:
          - ac
          - perception
          - will
        type: status
        value: "-4"
  Wounded:
    short_descr: You have been seriously injured.
    value: true
    override: false
