---
pf2e_deities:
  Althea:
    allowed_alignments:
    - LG
    - NG
    - CG
    - LN
    - N
    divine_font:
    - heal
    divine_skill: Medicine
    fav_weapon: Halberd
    domains:
    - Family
    - Healing
    - Pain
    - Duty
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must aid the suffering
    - Must assist those in need
    - Must assist those that seek atonement
    anathema:
    - Must not use violence when non-violence will serve
    - Must not use negative energy spells
    - May not betray the trust of a community
  Angoron:
    allowed_alignments:
    - CG
    - NG
    - LG
    - N
    - CN
    - LN
    divine_font:
    - harm
    - heal
    divine_skill: Athletics
    fav_weapon: Maul
    domains:
    - Confidence
    - Might
    - Ambition
    - Freedom
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must always protect those weaker than yourself
    - Must always try to do better than you did before
    - Must encourage the best in those around you
    anathema:
    - May not turn your back on a chance to challenge yourself
    - May not bully those weaker than yourself
    - May not fail to acknowledge when you’ve been bested
  Daeus:
    allowed_alignments:
    - LG
    - LN
    - NG
    divine_font:
    - heal
    divine_skill: Society
    fav_weapon: Longsword
    domains:
    - Wyrmkin
    - Truth
    - Zeal
    - Sun
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Justice isn’t perfect, always try to make it better
    - Must share the truths you learn
    - Must protect those who cannot defend themselves
    anathema:
    - May not abide injustice when you can step forward
    - May not choose for another who can choose for themselves
    - May not cheat, deceive, or undermine those who have placed trust in you
  Eluna:
    allowed_alignments:
    - NG
    - CG
    - LG
    - LN
    - N
    divine_font:
    - heal
    divine_skill: Arcana
    fav_weapon: starknife
    domains:
    - Moon
    - Magic
    - Dreams
    - Change
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Take the long view and always consider the greater good of all
    - Must use magic responsibly, and challenge those who do not
    - Seek to rescue those lycanthropes you can from the grip of Caracoroth
    anathema:
    - May not use spells or magic that deny the target their free will
    - May not sacrifice the future for short-term benefit
    - May not ignore the guidance found in dreams, divination, and prophecy
  Gilead:
    allowed_alignments:
    - NG
    - CG
    - N
    divine_font:
    - heal
    - harm
    divine_skill: Survival
    fav_weapon: Longbow
    domains:
    - Earth
    - Nature
    - Travel
    - Air
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must honor the hunt
    - Must defend wild spaces
    - May only kill what you must
    anathema:
    - Must not fail to bring down prey as cleanly as possible
    - The wild is to be protected, not smothered
    - Must allow the wild to enrich all
  Navos:
    allowed_alignments:
    - LN
    - LG
    - NG
    - N
    divine_font:
    - heal
    divine_skill: Acrobatics
    fav_weapon: unarmed
    domains:
    - Time
    - Secrecy
    - Perfection
    - Star
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must learn from the past, do not dwell on it
    - Be aware that you are making history now
    - Must seek to encourage the balance of time
    anathema:
    - Must not be consumed by something you cannot change
    - Must not fail to perceive your own actions
    - Must not try to change past events
  Tarien:
    allowed_alignments:
    - NG
    - CG
    - CN
    - N
    divine_font:
    - heal
    divine_skill: Stealth
    fav_weapon: Short Sword
    domains:
    - Luck
    - Travel
    - Trickery
    - Confidence
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must find the small joys in everything
    - Must understand that humility is the greatest teacher
    - It's only funny if others laugh too
    anathema:
    - Must not make a joke of someone who doesn’t deserve it
    - Must not dogpile someone already being shamed
    - Must not ringing harm with your humor
  Animus:
    allowed_alignments:
    - NG
    - LN
    - NE
    - N
    - CN
    divine_font:
    - heal
    - harm
    divine_skill: Arcana
    fav_weapon: quarterstaff
    domains:
    - Magic
    - Glyph
    - Knowledge
    - Fate
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - edict1
    - edict2
    - edict3
    anathema:
    - anathema1
    - anathema2
    - anathema3
  Ceinara:
    allowed_alignments:
    - NG
    - CG
    - CN
    - N
    - NE
    - CE
    divine_font:
    - heal or harm
    divine_ability: Charisma
    divine_skill: Performance
    fav_weapon: rapier
    domains:
    - Fire
    - Passion
    - Change
    - Creation
    cleric_spells:
    - Agitate
    - Fireball
    - Spirit Song
    edicts:
    - Must embrace your passions
    - Must patronize the arts and inspiration in all its forms.
    - Must delight in creation.
    anathema:
    - Must not support or protect the status quo, resort to rudeness when politeness will serve.
    - Must not discourage someone from their inspiration
    - Must not hide your emotions for any reason
  Dana:
    allowed_alignments:
    - NG
    - LN
    - N
    - CN
    - NE
    divine_font:
    - heal
    - harm
    divine_skill: Nature
    fav_weapon: scimitar
    domains:
    - Earth
    - Nature
    - Change
    - Swarm
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must defend nature’s bounty against those who would pillage it
    - Must honor the land as your mother; let none bring Her to harm
    - Must tend the gardens of the earth in all their forms
    anathema:
    - May not engage in wanton destruction
    - May not suffer the poisoning of the earth
    - Must not hunt rampantly
  Kor:
    allowed_alignments:
    - CG
    - CN
    - N
    - NE
    - CE
    divine_font:
    - harm
    divine_skill: Intimidation
    fav_weapon: Greataxe
    domains:
    - Zeal
    - Pain
    - Might
    - Destruction
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must be brave enough to fight at My side
    - Must be wise enough to achieve a glorious death
    - Must be prepared to train to achieve glory
    anathema:
    - Must never be the first to leave the battlefield
    - Must never mistake bravery for foolishness
    - Must never lie about your accomplishments
  Rada:
    allowed_alignments:
    - CG
    - LN
    - CN
    - LE
    - CE
    divine_font:
    - heal
    - harm
    divine_skill: Diplomacy
    fav_weapon: trident
    domains:
    - Water
    - Wealth
    - Travel
    - Air
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must honor a fair trade
    - The sea is owed a portion of your keep
    - Must harvest only what you need
    anathema:
    - Must never break a fair bargain
    - Must never be a false guide to another
    - Must not pollute the ocean
  Reos:
    allowed_alignments:
    - N
    - NG
    - NE
    - LN
    - LG
    - LE
    divine_font:
    - heal
    - harm
    divine_skill: Crafting
    fav_weapon: warhammer
    domains:
    - Earth
    - Creation
    - Perfection
    - Toil
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Always tinker - a thing can always be better
    - May never disrespect honest effort lacking skill
    - May never disrespect expertise
    anathema:
    - Must never engage in wonton destruction
    - Must never strive for impossible perfection
    - Must not disrespect the act of creation
  Serriel:
    allowed_alignments:
    - LG
    - LN
    - LE
    - NG
    - N
    divine_font:
    - heal
    - harm
    divine_skill: Society
    fav_weapon: lance
    domains:
    - Cities
    - Protection
    - Duty
    - Wealth
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must enrich your community
    - Honor the way of other communities
    - A thriving community is a growing one
    anathema:
    - Must never enrich yourself at the expense of your community
    - May never refuse to defend your community
    - Must not vandalizing a piece of cultural heritage
  Vardama:
    allowed_alignments:
    - LG
    - NG
    - LN
    - N
    - LE
    divine_font:
    - heal
    - harm
    divine_skill: Medicine
    fav_weapon: khopesh
    domains:
    - Death
    - Sorrow
    - Repose
    - Soul
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must guard the rest of the peaceful dead
    - Must offer succor to the grieving
    - Must try to ensure a peaceful passing
    anathema:
    - May not disturb the rest of the dead
    - May not judge the worth of a person
    - The fate of a soul is not yours to command
  Caracoroth:
    allowed_alignments:
    - CE
    - CN
    - NE
    divine_font:
    - harm
    divine_skill: Survival
    fav_weapon: unarmed
    domains:
    - Evil
    - Chaos
    - Animal
    - Madness
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must follow your instincts
    - Must not suffer the weak
    anathema:
    - May not be a coward
    - May not show weakness
    - May not talk when actions serve better
  Demios:
    allowed_alignments:
    - LN
    - N
    - LE
    - NE
    divine_font:
    - heal
    - harm
    divine_skill: Deception
    fav_weapon: whip
    domains:
    - Secrecy
    - Luck
    - Wealth
    - Ambition
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must use the truth to make your lies more plausible
    - Must lie so that you do not get caught
    - Must bear false witness where possible
    anathema:
    - May not tell the absolute truth
    - May not allow another to get the better of you in a lie
    - May not believe in innocence
  Gunahkar:
    allowed_alignments:
    - TN
    - CN
    - CE
    divine_font:
    - harm
    divine_skill: Survival
    fav_weapon: guisarme
    domains:
    - Chaos
    - Destruction
    - Death
    - Weather
    - Evil
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - May not stop suffering
    - May not fear sickness
    - Must endure all you can
    anathema:
    - Must not stop the faithful from feeling their pain
    - Must not fail to endure a trial
    - May not seek treatment for personal problems
  Maugrim:
    allowed_alignments:
    - LN
    - N
    - LE
    - NE
    divine_font:
    - harm
    divine_skill: Intimidation
    fav_weapon: greatsword
    domains:
    - Ambition
    - Toil
    - Tyranny
    - Perfection
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - edict1
    - edict2
    - edict3
    anathema:
    - anathema1
    - anathema2
    - anathema3
  Taara:
    allowed_alignments:
    - N
    - CN
    - NE
    - CE
    divine_font:
    - harm
    divine_skill: Deception
    fav_weapon: spiked chain
    domains:
    - Void
    - Darkness
    - Magic
    - Secrecy
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - edict1
    - edict2
    - edict3
    anathema:
    - anathema1
    - anathema2
    - anathema3
  Thul:
    allowed_alignments:
    - LN
    - N
    - CN
    - LE
    - NE
    - CE
    divine_font:
    - harm
    divine_skill: Occultism
    fav_weapon: scythe
    domains:
    - Undeath
    - Indulgence
    - Decay
    - Winter
    cleric_spells:
    - {}
    - {}
    - {}
    edicts:
    - Must not fear death
    - Must gather as much experience as you can
    - Must serve the dead where you can
    anathema:
    - May not fail to preserve memories
    - May not ignore the needs of the dead
    - May not live in fear of death
