---
pf2e_gear_options:
  shortcuts:
    i: gear
    in: gear
    inv: gear
    equip: gear/equip
    unequip: gear/unequip
    bag/put: bag/store
    bag/get: bag/retrieve
  use_encumbrance: true
  item_classes:
    weapons: PF2Weapon
    armor: PF2Armor
    bags: PF2Bag
    magicitem: PF2MagicItem
    shields: PF2Shield
  weapon_groups:
  - Axe
  - Bow
  - Brawling
  - Club
  - Dart
  - Flail
  - Hammer
  - Knife
  - Pick
  - Polearm
  - Shield
  - Sling
  - Spear
  - Sword
  armor_groups:
  - Cloth
  - Leather
  - Chain
  - Composite
  - Plate
