---
pf2e_skills:
  Acrobatics:
    key_abil: Dexterity
  Arcana:
    key_abil: Intelligence
    recall_knowledge: true
  Athletics:
    key_abil: Strength
  Crafting:
    key_abil: Intelligence
    recall_knowledge: true
  Deception:
    key_abil: Charisma
  Diplomacy:
    key_abil: Charisma
  Intimidation:
    key_abil: Charisma
  Medicine:
    key_abil: Wisdom
    recall_knowledge: true
  Nature:
    key_abil: Wisdom
    recall_knowledge: true
  Occultism:
    key_abil: Intelligence
    recall_knowledge: true
  Performance:
    key_abil: Charisma
  Religion:
    key_abil: Wisdom
    recall_knowledge: true
  Society:
    key_abil: Intelligence
    recall_knowledge: true
  Stealth:
    key_abil: Dexterity
  Survival:
    key_abil: Wisdom
  Thievery:
    key_abil: Dexterity

  Althean Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Angorite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Animusian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Caracorothan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Ceinaran Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Daeusite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Danan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Deimosian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Elunan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Gileadean Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Gunakharan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Illothan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Korite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Maugrimite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Navosian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Radan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Reosian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Serrielite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Taaran Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tarienite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Thulite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Alexandrian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Bryn Myridorn Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Dun Mordren Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tashraan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Hextus Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Vandalheim Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Cave Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Desert Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Plains Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Swamp Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Winterland Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Mountains Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Hills Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Island Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Demon Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Devil Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Vampire Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Academia Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Accounting Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Architecture Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Art Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Circus Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Engineering Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Farming Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Fey Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Fey Bullshit Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Fishing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Fortune-Telling Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Games Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Genealogy Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Gladiatorial Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Guild Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Heraldry Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Herbalism Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Hunting Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Labor Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Legal Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Library Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Mercantile Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Midwifery Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Milling Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Mining Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Sailing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Scouting Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Scribing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tanning Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Theater Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Underworld Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Warfare Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Alchemy Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Artistry Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Blacksmithing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Bookmaking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Glassmaking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Leatherworking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Pottery Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Shipbuilding Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Stonemasonry Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tailoring Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Weaving Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Woodworking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Slayer Lore: 
    key_abil: Intelligence
    recall_knowledge: true