---
pf2e_class:
  Alchemist:
    key_abil:
    - Intelligence
    HP: 8
    chargen:
      feat:
      - charclass
      charclass:
      - Infused Reagents
      - Advanced Alchemy
      attack:
        Simple Weapons: trained
        Alchemical Bombs: trained
        Unarmed: trained
      defense:
        Light Armor: trained
        Unarmored: trained
      Class DC: trained
      Perception: trained
      saves:
        Fortitude: expert
        Reflex: expert
        Will: trained
      skills_open: 3
      class_skills:
      - Crafting
      class_feats:
      - Alchemical Crafting
    advance:
      2:
        feat:
        - charclass
        - skill
      3:
        feat:
        - general
        boost:
        - skill
      4:
        feat:
        - charclass
        - skill
      5:
        boost:
        - ability
        - skill
        feat:
        - ancestry
        charclass:
        - Field Discovery
      6:
        feat:
        - charclass
        - skill
      7:
        attack:
          Simple Weapons: expert
          Alchemical Bombs: expert
        saves:
          Will: expert
        charclass:
        -  Perpetual Infusions
        feat:
        - general
        boost:
        - skill
      8:
        feat:
        - charclass
        - skill
      9:
        Class DC: expert
        Perception: expert
        charclass:
        - Double Brew
        feat:
        - ancestry
        boost:
        - skill
      10:
        boost:
        - ability
        feat:
        - charclass
        - skill
      11:
        feat:
        - general
        boost:
        - skill
        saves:
          Fortitude: master
        charclass:
        - Perpetual Potency
      12:
        feat:
        - charclass
        - skill
      13:
        feat:
        - ancestry
        boost:
        - skill
        charclass:
        - Greater Field Discovery
        - Weapon Specialization
        defense:
          Light Armor: expert
          Unarmored: expert
      14:
        feat:
        - charclass
        - skill
      15:
        boost:
        - ability
        - skill
        feat:
        - general
        charclass:
        - Alchemical Alacrity
        - Evasion
        saves:
          Reflex: master
      16:
        feat:
        - charclass
        - skill
      17:
        feat:
        - ancestry
        Class DC: master
        charclass:
        - Perpetual Perfection
        boost:
        - skill
      18:
        feat:
        - charclass
        - skill
      19:
        feat:
        - general
        boost:
        - skill
        defense:
          Light Armor: master
          Unarmored: master
      20:
        boost:
        - ability
        feat:
        - charclass
        - skill
    Barbarian:
      key_abil:
      - Strength
      HP: 12
      chargen:
        feat:
        - charclass
        attack:
          Simple Weapons: trained
          Martial Weapons: trained
          Unarmed: trained
        defense:
          Light Armor: trained
          Medium Armor: trained
          Unarmored: trained
        Class DC: trained
        Perception: expert
        saves:
          Fortitude: expert
          Reflex: trained
          Will: expert
        skills_open: 3
        class_skills:
        - Athletics
        action:
        - Rage
      advance: {}
    Bard:
      key_abil:
      - Charisma
      HP: 8
      chargen:
        Perception: expert
        saves:
          Fortitude: trained
          Reflex: trained
          Will: expert
        skills_open: 4
        skills:
        - Occultism
        - Performance
        attack:
          Simple Weapons: trained
          Bard Weapons: trained
          Unarmed: trained
        defense:
          Light Armor: trained
          Unarmored: trained
        spell_trad: occult
        Spells: trained
        spells_per_day:
          1: 2
        spells_known:
          cantrip: 5
          1: 2
        composition:
          cantrip:
          - Inspire Courage
          1:
          - Counter Performance
      advance:
        2:
          feat:
          - charclass
          - skill
          spells_per_day:
            1: 3
          spells_known:
            cantrip: 5
            1: 3
        3:
          spells_per_day:
            1: 3
            2: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 2
          feat:
          - general
          saves:
            Reflex: expert
          signature_spells:
            1: 1
            2: 1
          boost:
          - skill
        4:
          feat:
          - charclass
          - skill
          spells_per_day:
            1: 3
            2: 3
          spells_known:
            cantrip: 5
            1: 3
            2: 3
        5:
          boost:
          - ability
          - skill
          feat:
          - ancestry
          spells_per_day:
            1: 3
            2: 3
            3: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 2
        6:
          feat:
          - charclass
          - skill
          spells_per_day:
            1: 3
            2: 3
            3: 3
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
        7:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 2
          Spells: expert
          feat:
          - general
          boost:
          - skill
        8:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
          feat:
          - charclass
          - skill
        9:
          saves:
            Fortitude: expert
            Will: master
          charclass: Resolve
          boost:
          - skill
          feat:
          - ancestry
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 2
        10:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
          feat:
          - charclass
          - skill
          boost:
          - ability
        11:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 2
          feat:
          - general
          boost:
          - skill
          attack:
            Simple Weapons: expert
            Bard Weapons: expert
            Unarmed: expert
          Perception: master
        12:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
          feat:
          - charclass
          - skill
        13:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
            7: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
            7: 2
          defense:
            Light Armor: expert
            Unarmored: expert
          charclass:
          - Weapon Specialization
          boost:
          - skill
          feat:
          - ancestry
        14:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
            7: 3
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
            7: 3
          feat:
          - charclass
          - skill
        15:
          spells_per_day:
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
            7: 3
            8: 2
          spells_known:
            cantrip: 5
            1: 3
            2: 3
            3: 3
            4: 3
            5: 3
            6: 3
            7: 3
            8: 2
          feat:
          - general
          boost:
          - skill
          Spells: master
