pf2e_conditions:
  Blinded:
    short_descr: You're unable to see.
    value: false
    override: "Dazzled"
    rules:
      - key: "FlatModifier"
        selector: "perception"
        type: "status"
        value: -4
      - key: "Immunity"
        type: "visual"
  Clumsy:
    short_descr: Your movements become clumsy and inexact.
    value: true
    override: false
    rules:
      - key: "FlatModifier"
        selector: "dex-based"
        type: "status"
        value: "-@item.badge.value"
  Confused:
    short_descr: You lose your wits and attack wildly.
    value: false
    override: false
    rules:
      - key: "RollOption"
        option: "target:ally"
        value: false
      - key: "RollOption"
        option: "origin:ally"
        value: false
  Controlled:
    short_descr: You are no longer in control of your own actions.
    value: false
    override: false
  Dazzled:
    short_descr: Your eyes are overstimulated and you cannot see clearly.
    value: false
    override: false
  Deafened:
    short_descr: You cannot hear.
    value: false
    override: false
    rules:
      - key: "FlatModifier"
        selector: ["perception", "skill-check"]
        type: "status"
        value: -2
        predicate: [{"or": [{"and": ["check:type:skill", "item:trait:auditory"]}, {"and": ["check:statistic:base:perception", "check:statistic:initiative"]}]}]
      - key: "Immunity"
        type: "auditory"
      - key: "AdjustDegreeOfSuccess"
        selector: "perception"
        adjustment: {"all": "to-critical-failure"}
        predicate: ["item:trait:auditory"]
  Doomed:
    short_descr: A powerful force is pulling you towards death.
    value: true
    override: false
    daily: -1
  Drained:
    short_descr: You have lost some of your blood or life force.
    value: true
    override: false
    daily: -1
    rules:
      - key: "FlatModifier"
        selector: "con-based"
        type: "status"
        value: "-1 * @item.badge.value"
      - key: "FlatModifier"
        selector: "hp"
        type: "status"
        value: "min(-1 * @actor.level,-1) * @item.badge.value"
  Dying:
    short_descr: You are close to death.
    value: true
    override: false
  Encumbered:
    short_descr: You are carrying too much.
    value: false
    override: false
    rules:
      - key: "FlatModifier"
        selector: "all-speeds"
        value: -10
  Enfeebled:
    short_descr: You are physically weakened.
    value: true
    override: false
    rules:
      - key: "FlatModifier"
        selector: ["str-based", "str-damage"]
        type: "status"
        value: "-@item.badge.value"
  Fascinated:
    short_descr: You are compelled to focus your attention on something.
    value: false
    override: false
    rules:
      - key: "FlatModifier"
        selector: ["perception", "skill-check"]
        type: "status"
        value: -2
  Fatigued:
    short_descr: You are tired and cannot summon much energy.
    value: false
    override: false
    daily: false
    rules:
      - key: "FlatModifier"
        selector: ["ac", "saving-throw"]
        type: "status"
        value: -1
  Fleeing:
    short_descr: You can take no action other than running away.
    value: false
    override: false
  Frightened:
    short_descr: You are gripped by fear.
    value: true
    override: false
    rules:
      - key: "FlatModifier"
        selector: "all"
        type: "status"
        value: "-@item.badge.value"
  Grabbed:
    short_descr: You are being held by another creature.
    value: false
    override: false
  Immobilized:
    short_descr: You are unable to move.
    value: false
    override: false
  Invisible:
    short_descr: You cannot be seen.
    value: false
    override: false
  Off-Guard:
    short_descr: You are caught off-guard or otherwise unable to fully defend yourself.
    value: false
    override: false
    rules:
      - key: "FlatModifier"
        selector: "ac"
        type: "circumstance"
        value: -2
  Paralyzed:
    short_descr: You are frozen in place.
  Persistent:
    short_descr: You are taking damage over time from a source.
    value: true
    override: false
  Petrified:
    short_descr: You have been turned to stone.
    value: false
    override: false
  Prone:
    short_descr: You are lying on the ground.
    value: false
    override: false
    rules:
      - key: "FlatModifier"
        selector: "attack-roll"
        type: "circumstance"
        value: -2
  Quickened:
    short_descr: You move faster than normal.
    value: false
    override: false
  Restrained:
    short_descr: You are tied up and can barely move.
    value: false
    override: "Grabbed"
  Sickened:
    short_descr: You feel ill.
    value: true
    override: false
    rules:
      - key: "FlatModifier"
        selector: "all"
        type: "status"
        value: "-@item.badge.value"
  Slowed:
    short_descr: You move more slowly than normal.
    value: true
    override: false
  Stunned:
    short_descr: You are reeling and unable to use your senses.
    value: true
    override: "Slowed"
  Stupefied:
    short_descr: Your thoughts are cloudy and indistinct.
    value: true
    override: false
    rules:
      - key: "FlatModifier"
        selector: ["cha-based", "int-based", "wis-based"]
        type: "status"
        value: "-@item.badge.value"
  Unconscious:
    short_descr: You are sleeping or knocked out.
    value: false
    override: false
    rules:
      - key: "FlatModifier"
        selector: ["ac", "perception", "reflex"]
        type: "status"
        value: -4
  Wounded:
    short_descr: You have been seriously injured.
    value: true
    override: false
