---
pf2e_feats:
  Alchemist Dedication:
    assoc_charclass:
    - Alchemist
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: Become a multiclass alchemist.
    prereq:
      level: 2
      ability: 
      - Intelligence/14
    feat_type: 
    - Dedication
  Barbarian Dedication:
    assoc_charclass:
    - Barbarian
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: Become a multiclass barbarian.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Constitution/14
    feat_type: 
    - Dedication
  Bard Dedication:
    assoc_charclass:
    - Bard
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: Become a multiclass bard.
    prereq:
      level: 2
      ability: 
      - Charisma/14
    feat_type: 
    - Dedication
  Champion Dedication:
    assoc_charclass:
    - Champion
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass champion.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Charisma/14
    feat_type: 
    - Dedication
  Cleric Dedication:
    assoc_charclass:
    - Cleric
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass cleric.
    prereq:
      level: 2
      ability: 
      - Wisdom/14
    feat_type: 
    - Dedication
  Druid Dedication:
    assoc_charclass:
    - Druid
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass druid.
    prereq:
      level: 2
      ability: 
      - Wisdom/14
    feat_type: 
    - Dedication
  Fighter Dedication:
    assoc_charclass:
    - Fighter
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become trained in simple weapons and martial weapons.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Dexterity/14
    feat_type: 
    - Dedication
  Investigator Dedication:
    assoc_charclass:
    - Investigator
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You gain the on the case class feature, which grants you both the Pursue a Lead activity and Clue In reaction.
    prereq:
      level: 2
      ability: 
      - Intelligence/14
    feat_type: 
    - Dedication
  Monk Dedication:
    assoc_charclass:
    - Monk
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass monk.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Dexterity/14
    feat_type: 
    - Dedication
  Oracle Dedication:
    assoc_charclass:
    - Oracle
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass oracle.
    prereq:
      level: 2
      ability: 
      - Charisma/14
    feat_type: 
    - Dedication
  Ranger Dedication:
    assoc_charclass:
    - Ranger
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass ranger.
    prereq:
      level: 2
      ability: 
      - Dexterity/14
    feat_type: 
    - Dedication
  Rogue Dedication:
    assoc_charclass:
    - Rogue
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass rogue.
    prereq:
      level: 2
      ability: 
      - Dexterity/14
    feat_type: 
    - Dedication
  Sorcerer Dedication:
    assoc_charclass:
    - Sorcerer
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass sorcerer.
    prereq:
      level: 2
      ability: 
      - Charisma/14
    feat_type: 
    - Dedication
  Witch Dedication:
    assoc_charclass:
    - Witch
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You cast spells like a witch.
    prereq:
      level: 2
      ability: 
      - Intelligence/14
    feat_type: 
    - Dedication
  Wizard Dedication:
    assoc_charclass:
    - Witch
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass wizard
    prereq:
      level: 2
      ability: 
      - Intelligence/14
    feat_type: 
    - Dedication
