pf2e_conditions:
  Blinded:
    short_descr: You're unable to see.
    value: false
    affected_stat:
      Perception: -4
    override: "Dazzled"
  Clumsy:
    short_descr: Your movements become clumsy and inexact.
    value: true
    affected_stat:
    - "Dexterity"
    override: false
  Confused:
    short_descr: You lose your wits and attack wildly.
    value: false
    override: false
  Controlled:
    short_descr: You are no longer in control of your own actions.
    value: false
    override: false
  Dazzled:
    short_descr: Your eyes are overstimulated and you cannot see clearly.
    value: false
    override: false
  Deafened:
    short_descr: You cannot hear.
    value: false
    affected_stat:
      Perception: -2
    override: false
  Doomed:
    short_descr: A powerful force is pulling you towards death.
    value: true
    override: false
    daily: -1
  Drained:
    short_descr: You have lost some of your blood or life force.
    value: true
    override: false
    affected_stat:
    - "Constitution"
    daily: -1
  Dying:
    short_descr: You are close to death.
    value: true
    override: false
  Encumbered:
    short_descr: You are carrying too much.
    value: false
    affected_stat:
      Dexterity: -1
      Speed: -10
    override: false
  Enfeebled:
    short_descr: You are physically weakened.
    value: true
    affected_stat:
    - "Strength"
    override: false
  Fascinated:
    short_descr: You are compelled to focus your attention on something.
    value: false
    override: false
    affected_stat:
      Perception: -2
  Fatigued:
    short_descr: You are tired and cannot summon much energy.
    value: false
    affected_stat:
      Base AC: -1
      Fortitude: -1
      Reflex: -1
      Will: -1
    override: false
    daily: false
  Flat-Footed:
    short_descr: You are caught off-guard or otherwise unable to fully defend yourself.
    value: false
    override: false
    affected_stat:
      Base AC: -2
  Fleeing:
    short_descr: You can take no action other than running away.
    value: false
    override: false
  Frightened:
    short_descr: You are gripped by fear.
    value: true
    override: false
  Grabbed:
    short_descr: You are being held by another creature.
    value: false
    override: false
  Immobilized:
    short_descr: You are unable to move.
    value: false
    override: false
  Invisible:
    short_descr: You cannot be seen.
    value: false
    override: false
  Paralyzed:
    short_descr: You are frozen in place.
  Persistent:
    short_descr: You are taking damage over time from a source.
    value: true
    override: false
  Petrified:
    short_descr: You have been turned to stone.
    value: false
    override: false
  Prone:
    short_descr: You are lying on the ground.
    value: false
    override: false
  Quickened:
    short_descr: You move faster than normal.
    value: false
    override: false
  Restrained:
    short_descr: You are tied up and can barely move.
    value: false
    override: "Grabbed"
  Sickened:
    short_descr: You feel ill.
    value: true
    override: false
  Slowed:
    short_descr: You move more slowly than normal.
    value: true
    override: false
  Stunned:
    short_descr: You are reeling and unable to use your senses.
    value: true
    override: "Slowed"
  Stupefied:
    short_descr: Your thoughts are cloudy and indistinct.
    affected_stat:
    - "Intelligence"
    - "Wisdom"
    - "Charisma"
    value: true
    override: false
  Unconscious:
    short_descr: You are sleeping or knocked out.
    value: false
    override: false
  Wounded:
    short_descr: You have been seriously injured.
    value: true
    override: false
