---
pf2e_classes:
   Alchemist:
      Key Score: Intelligence
      Secondary Scores:
      - Constitution
      - Dexterity
      Perception: trained
      Saves:
         Fortitude: expert
         Reflex: expert
         Will: trained
      Class Skills:
         Crafting: trained
         open: 3
      Attacks:
         Simple Weapons: trained
         Alchemical Bombs: trained
         Unarmed: trained
      Class DC: trained
