---
pf2_ammunition:
  Arrows:
    amount: 10
    bulk: 0.1
    price: 10
    level: 0
  Blowgun Darts:
    amount: 10
    bulk: 0.1
    level: 0
    price: 5
  Bolts:
    amount: 10
    bulk: 0.1
    level: 0
  Sling Bullets:
    amount: 10
    bulk: 0.1
    level: 0
    price: 1
