---
pf2e_background:
  Acolyte:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Religion
    lores:
    - Scribing Lore
    feats:
    - Student of the Canon
    special: []
  Acrobat:
    req_abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Acrobatics
    lores:
    - Circus
    feats:
    - Steady Balance
    special: []
  Amnesiac:
    abl_boosts:
    - open
    - open
    - open
    skills: []
    feats: []
    special: "Amnesiac"
    rare: true
  Animal Whisperer:
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Society
    lores:
    - Architecture
    feats:
    - Additional Lore
  Artisan:
    abl_boosts:
    - [ Strength, Intelligence ]
    - open
    skills:
    - Crafting
    lores:
    - Guild Lore
    feats:
    - Specialty Crafting
    special: []
  Artist:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Crafting
    lores:
    - Art Lore
    feats:
    - Specialty Crafting
    special: []
  Bandit:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Intimidation
    lores:
    - Desert Lore
    - Plains Lore
    - Swamp Lore
    - Winterland Lore
    - Mountains Lore
    - Hills Lore
    - Island Lore
    feats:
    - Group Coercion
    special: []
  Barber:
    abl_boosts:
    - [ Dexterity, Wisdom ]
    - open
    skills:
    - Medicine
    lores:
    - Surgery Lore
    feats:
    - Risky Surgery
    special: []
  Barkeep:
    abl_boosts:
    - [ Constitution, Charisma ]
    - open
    skills:
    - Diplomacy
    lores:
    - Alcohol Lore
    feats:
    - Hobnobber
    special: []
  Barrister:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Diplomacy
    lores:
    - Legal Lore
    feats:
    - Group Impression
    special: []
  Blessed:
    abl_boosts:
    - [ Wisdom, Charisma ]
    - open
    lores:
    - deity
    feats: []
    special: "Blessed: 1st level divine innate spell at will"
    rare: true
  Bookkeeper:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Society
    lores:
    - Accounting Lore
    feats:
    - Eye For Numbers
    special: []
  Bounty Hunter:
    abl_boosts:
    - [ Strength, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - Legal Lore
    feats:
    - Experienced Tracker
    special: []
  Charlatan:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Deception
    lores:
    - Underworld Lore
    feats:
    - Charming Liar
    special: []
  Cook:
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Survival
    lores:
    - Cooking Lore
    feats:
    - Seasoned
    special: []
  Courier:
    abl_boosts:
    - [ Dexterity, Intelligence ]
    - open
    skills:
    - Society
    lores:
    - city
    feats:
    - Glean Contents
    special: []
  Criminal:
    abl_boosts:
    - [ Dexterity, Intelligence ]
    - open
    skills:
    - Stealth
    lores:
    - Underworld Lore
    feats:
    - Experienced Smuggler
    special: []
  Cultist:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Occultism
    lores:
    - deity
    feats:
    - Schooled In Secrets
    special: []
  Cursed:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Occultism
    lores:
    - Curse Lore
    feats: []
    reaction:
    - Warding Sign
    rare: true
  Detective:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Society
    lores:
    - Underworld Lore
    feats:
    - Streetwise
    special: []
  Emissary:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Society
    lores:
    - city
    feats:
    - Multilingual
    special: []
  Entertainer:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Performance
    lores:
    - Theater Lore
    feats:
    - Fascinating Performance
    special: []
  Farmhand:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Athletics
    lores:
    - Farming Lore
    feats:
    - Assurance - Athletics
    special: []
  Feral Child:
    abl_boosts:
    - [ Strength, Dexterity, Constitution ]
    skills:
    - Nature
    - Survival
    feats:
    - Forager
    special:
    - Low-Light Vision
    - Imprecise Scent
    rare: true
  Feybound:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Nature
    lores:
    - Fey Lore
    feats: []
    free action:
    - "Fey's Fortune"
    rare: true
  Field Medic:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Medicine
    lores:
    - Warfare Lore
    feats:
    - Battle Medicine
    special: []
  Fortune Teller:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Occultism
    lores:
    - Fortune-Telling Lore
    feats:
    - Lie To Me
    special: []
  Gambler:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Deception
    lores:
    - Games Lore
    feats:
    - Lie To Me
    special: []
  Gladiator:
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Performance
    lores:
    - Gladiatorial Lore
    feats:
    - Impressive Performance
    special: []
  Guard:
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Intimidation
    lores:
    - Legal Lore
    - Warfare Lore
    feats:
    - Quick Coercion
    special: []
  Harrow-Led:
    abl_boost:
    - open
    skills:
    - Occultism
    - Performance
    - Society
    lores:
    - Harrow Lore
    feats:
    - Dubious Knowledge
    special: Harrow
  Haunted:
    abl_boosts:
    - [ Wisdom, Charisma ]
    - open
    skills:
    - Occultism
    feats: []
    special: "Haunted: free skill + circumstance"
    rare: true
  Herbalist:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Nature
    lores:
    - Herbalism Lore
    feats:
    - Natural Medicine
    special: []
  Hermit:
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Nature
    - Occultism
    lores:
    - terrain
    feats:
    - Dubious Knowledge
    special: []
  Hunter:
    abl_boosts:
    - [ Dexterity, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - Tanning Lore
    feats:
    - Survey Wildlife
    special: []
  Insurgent:
    abl_boosts:
    - [ Strength, Wisdom ]
    - open
    skills:
    - Deception
    lores:
    - Warfare Lore
    feats:
    - Lengthy Diversion
    special: []
  Laborer:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Athletics
    lores:
    - Labor Lore
    feats:
    - Hefty Hauler
  Martial Disciple:
    abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Acrobatics
    - Athletics
    lores:
    - Warfare Lore
    feats:
    - Cat Fall
    - Quick Jump
    special: []
  Merchant:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Diplomacy
    lores:
    - Mercantile Lore
    feats:
    - Bargain Hunter
    special: []
  Miner:
    abl_boosts:
    - [ Strength, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - Mining Lore
    feats:
    - Terrain Expertise - Underground
    special: []
  Noble:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Society
    lores:
    - Genealogy Lore
    feats:
    - Courtly Graces
    special: []
  Nomad:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - terrain
    feats:
    - Assurance - Survival
    special: []
  Outrider:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Nature
    lores:
    - Plains Lore
    feats:
    - Express Rider
    special: []
  Pilgrim:
    abl_boosts:
    - [ Wisdom, Charisma ]
    - open
    skills:
    - Religion
    lores:
    - deity
    feats:
    - "Pilgrim's Token"
    special: []
  Prisoner:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Stealth
    lores:
    - Underworld Lore
    feats:
    - Experienced Smuggler
    special: []
  Refugee:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Society
    lores:
    - city
    feats:
    - Streetwise
    special: []
  Returned:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills: []
    feats:
    - [ "Diehard", "Additional Lore - Boneyard Lore" ]
    special: []
    rare: true
  Root Worker:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Occultism
    lores:
    - Herbalism Lore
    feats:
    - Root Magic
    special: []
  Sailor:
    abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Athletics
    - Acrobatics
    lores:
    - Sailing Lore
    feats:
    - Underwater Marauder
    - Cat Fall
    special: []
  Scavenger:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - city
    feats:
    - Forager
    special: []
  Scholar:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Arcana
    - Nature
    - Occultism
    - Religion
    lores:
    - Academia Lore
    feats:
    - Assurance - SKILL_CHOICE
    special: []
  Scout:
    abl_boosts:
    - [ Dexterity, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - terrain
    feats:
    - Forager
    special: []
  Servant:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Society
    lores:
    - Labor Lore
    feats:
    - Read Lips
    special: []
  Spell Seeker:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Arcana
    - Occultism
    lores:
    - Library Lore
    feats:
    - Recognize Spell
    special: []
  Squire:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Athletics
    lores:
    - Heraldry Lore
    - Warfare Lore
    feats:
    - Armor Assist
    special: []
  Street Urchin:
    abl_boosts:
    - [ Dexterity, Constitution ]
    - open
    skills:
    - Thievery
    lores:
    - city
    feats:
    - Pickpocket
    special: []
  Tax Collector:
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Intimidation
    lores:
    - city
    feats:
    - Quick Coercion
    special: []
  Teacher:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Performance
    - Society
    lores:
    - Academia Lore
    feats:
    - Experienced Professional
    special: []
  Tinker:
    abl_boosts:
    - [ Dexterity, Intelligence ]
    - open
    skills:
    - Crafting
    lores:
    - Engineering Lore
    feats:
    - Specialty Crafting
    special: []
  Trailblazer:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - Cartography Lore
    feats:
    - Terrain Expertise - TERRAIN
    special: []
  Translator:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Society
    lores:
    - Scribing Lore
    feats:
    - Multilingual
    special: []
  Ward:
    abl_boosts:
    - [ Constitution, Charisma ]
    - open
    skills:
    - Performance
    lores:
    - Genealogy Lore
    feats:
    - Fascinating Performance
    special: []
  Warrior:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Intimidation
    lores:
    - Warfare Lore
    feats:
    - Intimidating Glare
    special: []
