---
pf2e_bags:
  Backpack:
    price: 10
    level: 0
    bulk: 0
    bulk_bonus: 2
    capacity: 4
  Chest:
    price: 60
    level: 0
    bulk: 2
    bulk_bonus: 0
    capacity: 8
  Sack:
    price: 1
    level: 0
    bulk: 0.1
    capacity: 8
    bulk_bonus: 0
