---
pf2e_feats:
  Alchemist Dedication:
    assoc_charclass:
    - Alchemist
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: Become a multiclass alchemist.
    prereq:
      level: 2
      ability: 
      - Intelligence/14
  Barbarian Dedication:
    assoc_charclass:
    - Barbarian
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: Become a multiclass barbarian.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Constitution/14
  Bard Dedication:
    assoc_charclass:
    - Bard
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: Become a multiclass bard.
    prereq:
      level: 2
      ability: 
      - Charisma/14
  Champion Dedication:
    assoc_charclass:
    - Champion
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass champion.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Charisma/14
  Cleric Dedication:
    assoc_charclass:
    - Cleric
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass cleric.
    prereq:
      level: 2
      ability: 
      - Wisdom/14
  Druid Dedication:
    assoc_charclass:
    - Druid
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass druid.
    prereq:
      level: 2
      ability: 
      - Wisdom/14
  Fighter Dedication:
    assoc_charclass:
    - Fighter
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become trained in simple weapons and martial weapons.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Dexterity/14
  Investigator Dedication:
    assoc_charclass:
    - Investigator
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You gain the on the case class feature, which grants you both the Pursue a Lead activity and Clue In reaction.
    prereq:
      level: 2
      ability: 
      - Intelligence/14
  Monk Dedication:
    assoc_charclass:
    - Monk
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass monk.
    prereq:
      level: 2
      ability: 
      - Strength/14
      - Dexterity/14
  Oracle Dedication:
    assoc_charclass:
    - Oracle
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass oracle.
    prereq:
      level: 2
      ability: 
      - Charisma/14
  Ranger Dedication:
    assoc_charclass:
    - Ranger
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass ranger.
    prereq:
      level: 2
      ability: 
      - Dexterity/14
  Rogue Dedication:
    assoc_charclass:
    - Rogue
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass rogue.
    prereq:
      level: 2
      ability: 
      - Dexterity/14
  Sorcerer Dedication:
    assoc_charclass:
    - Sorcerer
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass sorcerer.
    prereq:
      level: 2
      ability: 
      - Charisma/14
  Witch Dedication:
    assoc_charclass:
    - Witch
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You cast spells like a witch.
    prereq:
      level: 2
      ability: 
      - Intelligence/14
  Wizard Dedication:
    assoc_charclass:
    - Witch
    traits:
    - archetype
    - dedication
    - multiclass
    shortdesc: You become a multiclass wizard
    prereq:
      level: 2
      ability: 
      - Intelligence/14
