---
pf2e_background:
  Acolyte:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Religion
    - Scribing Lore
    feat:
    - Student of the Canon
    special: []
    action: []
    reaction: []
  Acrobat:
    req_abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Acrobatics
    - Circus Lore
    feat:
    - Steady Balance
    special: []
    action: []
    reaction: []
  Animal Whisperer:
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Society
    - Architecture Lore
    feat:
    - Additional Lore
    action: []
    reaction: []
  Artisan:
    abl_boosts:
    - [ Strength, Intelligence ]
    - open
    skills:
    - Crafting
    - Guild Lore
    feat:
    - Specialty Crafting
    special: []
    action: []
    reaction: []
  Artist:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Crafting
    - Art Lore
    feat:
    - Specialty Crafting
    special: []
    action: []
    reaction: []
  Bandit:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Intimidation
    lores:
    - terrain
    feat:
    - Group Coercion
    special: []
    action: []
    reaction: []
  Barber:
    abl_boosts:
    - [ Dexterity, Wisdom ]
    - open
    skills:
    - Medicine
    - Surgery Lore
    feat:
    - Risky Surgery
    special: []
    action: []
    reaction: []
  Barkeep:
    abl_boosts:
    - [ Constitution, Charisma ]
    - open
    skills:
    - Diplomacy
    - Alcohol Lore
    feat:
    - Hobnobber
    special: []
    action: []
    reaction: []
  Barrister:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Diplomacy
    - Legal Lore
    feat:
    - Group Impression
    special: []
    action: []
    reaction: []
  Blessed:
    abl_boosts:
    - [ Wisdom, Charisma ]
    - open
    lores:
    - deity
    feat: []
    rare: true
    action: []
    reaction: []
  Bookkeeper:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Society
    - Accounting Lore
    feat:
    - Eye For Numbers
    special: []
    action: []
    reaction: []
  Bounty Hunter:
    abl_boosts:
    - [ Strength, Wisdom ]
    - open
    skills:
    - Survival
    - Legal Lore
    feat:
    - Experienced Tracker
    special: []
  Charlatan:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Deception
    - Underworld Lore
    feat:
    - Charming Liar
    special: []
    action: []
    reaction: []
  Cook:
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Survival
    - Cooking Lore
    feat:
    - Seasoned
    special: []
    action: []
    reaction: []
  Courier:
    abl_boosts:
    - [ Dexterity, Intelligence ]
    - open
    skills:
    - Society
    lores:
    - city
    feat:
    - Glean Contents
    special: []
    action: []
    reaction: []
  Criminal:
    abl_boosts:
    - [ Dexterity, Intelligence ]
    - open
    skills:
    - Stealth
    - Underworld Lore
    feat:
    - Experienced Smuggler
    special: []
    action: []
    reaction: []
  Cultist:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Occultism
    lores:
    - deity
    feat:
    - Schooled In Secrets
    special: []
    action: []
    reaction: []
  Cursed:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Occultism
    - Curse Lore
    feat: []
    reaction:
    - Warding Sign
    rare: true
    action: []
  Detective:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Society
    - Underworld Lore
    feat:
    - Streetwise
    special: []
    action: []
    reaction: []
  Emissary:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Society
    lores:
    - city
    feat:
    - Multilingual
    special: []
    action: []
    reaction: []
  Entertainer:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Performance
    - Theater Lore
    feat:
    - Fascinating Performance
    special: []
    action: []
    reaction: []
  Farmhand:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Athletics
    - Farming Lore
    feat:
    - Assurance (Athletics)
    special: []
    action: []
    reaction: []
  Feral Child:
    abl_boosts:
    - [ Strength, Dexterity, Constitution ]
    skills:
    - Nature
    - Survival
    feat:
    - Forager
    special:
    - Low-Light Vision
    - Imprecise Scent
    rare: true
    action: []
    reaction: []
  Feybound:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills: 
    - Fey Lore
    feat: []
    action:
    - "Fey's Fortune"
    rare: true
    reaction: []
    special: []
  Field Medic:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Medicine
    - Warfare Lore
    feat:
    - Battle Medicine
    special: []
    action: []
    reaction: []
  Fortune Teller:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Occultism
    - Fortune-Telling Lore
    feat:
    - Lie To Me
    special: []
  Gambler:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Deception
    - Games Lore
    feat:
    - Lie To Me
    special: []
  Gladiator:
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Performance
    - Gladiatorial Lore
    feat:
    - Impressive Performance
    special: []
    action: []
    reaction: []
  Guard (Legal Lore):
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Intimidation
    - Legal Lore
    feat:
    - Quick Coercion
    special: []
    action: []
    reaction: []
  Guard (Warfare Lore):
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Intimidation
    - Warfare Lore
    feat:
    - Quick Coercion
    special: []
    action: []
    reaction: []
  Harrow-Led (Occultism):
    abl_boost:
    - open
    skills:
    - Occultism
    - Harrow Lore
    feat:
    - Dubious Knowledge
    special:
    - Harrow
    action: []
    reaction: []
  Harrow-Led (Performance):
    abl_boost:
    - open
    skills:
    - Performance
    - Harrow Lore
    feat:
    - Dubious Knowledge
    special:
    - Harrow
    action: []
    reaction: []
  Harrow-Led (Society):
    abl_boost:
    - open
    skills:
    - Society
    - Harrow Lore
    feat:
    - Dubious Knowledge
    special:
    - Harrow
    action: []
    reaction: []
  Haunted:
    abl_boosts:
    - [ Wisdom, Charisma ]
    - open
    skills:
    - Occultism
    feat: []
    special:
    - Haunted
    rare: true
    action: []
    reaction: []
  Herbalist:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Nature
    - Herbalism Lore
    feat:
    - Natural Medicine
    special: []
    action: []
    reaction: []
  Hermit (Nature):
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Nature
    lores:
    - terrain
    feat:
    - Dubious Knowledge
    special: []
    action: []
    reaction: []
  Hermit (Occultism):
    abl_boosts:
    - [ Constitution, Intelligence ]
    - open
    skills:
    - Occultism
    lores:
    - terrain
    feat:
    - Dubious Knowledge
    special: []
    action: []
    reaction: []
  Hunter:
    abl_boosts:
    - [ Dexterity, Wisdom ]
    - open
    skills:
    - Survival
    - Tanning Lore
    feat:
    - Survey Wildlife
    special: []
    action: []
    reaction: []
  Insurgent:
    abl_boosts:
    - [ Strength, Wisdom ]
    - open
    skills:
    - Deception
    - Warfare Lore
    feat:
    - Lengthy Diversion
    special: []
    action: []
    reaction: []
  Laborer:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Athletics
    - Labor Lore
    feat:
    - Hefty Hauler
    special: []
    action: []
    reaction: []
  Martial Disciple (Acrobatics):
    abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Acrobatics
    - Warfare Lore
    feat:
    - Cat Fall
    - Quick Jump
    special: []
    action: []
    reaction: []
  Martial Disciple (Athletics):
    abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Athletics
    - Warfare Lore
    feat:
    - Cat Fall
    - Quick Jump
    special: []
    action: []
    reaction: []
  Merchant:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Diplomacy
    - Mercantile Lore
    feat:
    - Bargain Hunter
    special: []
    action: []
    reaction: []
  Miner:
    abl_boosts:
    - [ Strength, Wisdom ]
    - open
    skills:
    - Survival
    - Mining Lore
    feat:
    - Terrain Expertise/Underground
    special: []
    action: []
    reaction: []
  Noble:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Society
    - Genealogy Lore
    feat:
    - Courtly Graces
    special: []
    action: []
    reaction: []
  Nomad:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - terrain
    feat:
    - Assurance/Survival
    special: []
    action: []
    reaction: []
  Outrider:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Nature
    - Plains Lore
    feat:
    - Express Rider
    special: []
    action: []
    reaction: []
  Pilgrim:
    abl_boosts:
    - [ Wisdom, Charisma ]
    - open
    skills:
    - Religion
    lores:
    - deity
    feat:
    - "Pilgrim's Token"
    special: []
    action: []
    reaction: []
  Prisoner:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Stealth
    - Underworld Lore
    feat:
    - Experienced Smuggler
    special: []
    action: []
    reaction: []
  Refugee:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Society
    lores:
    - city
    feat:
    - Streetwise
    special: []
    action: []
    reaction: []
  Returned:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills: 
    - Boneyard Lore
    feat:
    - Diehard
    - Additional Lore/Boneyard Lore
    special: []
    rare: true
    action: []
    reaction: []
  Root Worker:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Occultism
    - Herbalism Lore
    feat:
    - Root Magic
    special: []
    action: []
    reaction: []
  Sailor:
    abl_boosts:
    - [ Strength, Dexterity ]
    - open
    skills:
    - Athletics
    - Sailing Lore
    feat:
    - Underwater Marauder
    - Cat Fall
    special: []
    action: []
    reaction: []
  Scavenger:
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - city
    feat:
    - Forager
    special: []
    action: []
    reaction: []
  Scholar (Arcana):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Arcana
    - Academia Lore
    feat: []
    special: []
    action: []
    reaction: []
  Scholar (Nature):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Nature
    - Academia Lore
    feat: []
    special: []
    action: []
    reaction: []
  Scholar (Occultism):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Occultism
    - Academia Lore
    feat: []
    special: []
    action: []
    reaction: []
  Scholar (Religion):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Religion
    - Academia Lore
    feat: []
    special: []
    action: []
    reaction: []
  Scout:
    abl_boosts:
    - [ Dexterity, Wisdom ]
    - open
    skills:
    - Survival
    lores:
    - terrain
    feat:
    - Forager
    special: []
    action: []
    reaction: []
  Servant:
    abl_boosts:
    - [ Dexterity, Charisma ]
    - open
    skills:
    - Society
    - Labor Lore
    feat:
    - Read Lips
    special: []
    action: []
    reaction: []
  Spell Seeker (Arcana):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Arcana
    - Library Lore
    feat:
    - Recognize Spell
    special: []
    action: []
    reaction: []
  Spell Seeker (Occultism):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Occultism
    - Library Lore
    feat:
    - Recognize Spell
    special: []
    action: []
    reaction: []
  Squire (Heraldry Lore):
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Athletics
    - Heraldry Lore
    feat:
    - Armor Assist
    special: []
    action: []
    reaction: []
  Squire (Warfare Lore):
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Athletics
    - Warfare Lore
    feat:
    - Armor Assist
    special: []
    action: []
    reaction: []
  Street Urchin:
    abl_boosts:
    - [ Dexterity, Constitution ]
    - open
    skills:
    - Thievery
    lores:
    - city
    feat:
    - Pickpocket
    special: []
    action: []
    reaction: []
  Tax Collector:
    abl_boosts:
    - [ Strength, Charisma ]
    - open
    skills:
    - Intimidation
    lores:
    - city
    feat:
    - Quick Coercion
    special: []
    action: []
    reaction: []
  Teacher (Performance):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Performance
    - Academia Lore
    feat:
    - Experienced Professional
    special: []
    action: []
    reaction: []
  Teacher (Society):
    abl_boosts:
    - [ Intelligence, Wisdom ]
    - open
    skills:
    - Society
    - Academia Lore
    feat:
    - Experienced Professional
    special: []
    action: []
    reaction: []
  Tinker:
    abl_boosts:
    - [ Dexterity, Intelligence ]
    - open
    skills:
    - Crafting
    - Engineering Lore
    feat:
    - Specialty Crafting
    special: []
    action: []
    reaction: []
  Trailblazer:
    abl_boosts:
    - [ Constitution, Wisdom ]
    - open
    skills:
    - Survival
    - Cartography Lore
    feat: []
    special: []
    action: []
    reaction: []
  Translator:
    abl_boosts:
    - [ Intelligence, Charisma ]
    - open
    skills:
    - Society
    - Scribing Lore
    feat:
    - Multilingual
    special: []
    action: []
    reaction: []
  Ward:
    abl_boosts:
    - [ Constitution, Charisma ]
    - open
    skills:
    - Performance
    - Genealogy Lore
    feat:
    - Fascinating Performance
    special: []
    action: []
    reaction: []
  Warrior:
    abl_boosts:
    - [ Strength, Constitution ]
    - open
    skills:
    - Intimidation
    - Warfare Lore
    feat:
    - Intimidating Glare
    special: []
    action: []
    reaction: []
