---
pf2e:
  achievements:
    dungeon_keeper:
      type: community
      message: Ran %{count} Player-Run Plots.
      levels:
      - 1
      - 10
      - 25
      - 50
      - 100
      - 250
      - 500
    master_of_meetups:
      type: community
      message: Ran %{count} Meetups.
      levels:
      - 1
      - 10
      - 25
      - 50
      - 100
      - 250
      - 500
  shortcuts:
    sheet/top: sheet/info
    rollalias: roll/alias
    remalias: roll/alias
    listalias: roll/listalias
    rollfor: roll/for
    csheet: sheet/combat
  allowed_alignments:
  - LG
  - NG
  - CG
  - LN
  - N
  - CN
  roll_channel: 'Rolls'
  can_select_language:
  - common
  - uncommon
  open_sheets: true
  open_npc_sheets: false
  title_color: '%x172'
  list_item: '%x229'
  use_alignment: true
  use_untrained_improv: false
  subclass_names:
    Alchemist: 'Research Field'
    Barbarian: 'Instinct'
    Bard: 'Muse'
    Champion: 'Cause'
    Druid: 'Order'
    Ranger: "Hunter's Edge"
    Rogue: 'Racket'
    Sorcerer: 'Bloodline'
    Wizard: 'School'
    Investigator: 'Methodology'
    Oracle: 'Mystery'
    Witch: 'Patron'
  condition_colors:
    Dying: '%xr'
    Wounded: '%xy'
    Drained: '%xh%xx'
    Doomed: '%x172'
  permissions:
    modify_sheet: Modify character sheets.
    view_sheets: View other people's character sheets (if sheets are closed).
    kill_pc: (Associated to DM role) Has the ability to inflict Drained, Doomed, and Dead conditions on PC's.
