---
pf2e_lores:
  deity:
  - Althean Lore
  - Angorite Lore
  - Animusian Lore
  - Caracorothan Lore
  - Ceinaran Lore
  - Daeusite Lore
  - Danan Lore
  - Deimosian Lore
  - Elunan Lore
  - Gileadean Lore
  - Gunakharan Lore
  - Illothan Lore
  - Korite Lore
  - Maugrimite Lore
  - Navosian Lore
  - Radan Lore
  - Reosian Lore
  - Serrielite Lore
  - Taaran Lore
  - Tarienite Lore
  - Thulite Lore
  city:
  - Alexandrian Lore
  - Bryn Myridorn Lore
  - Dun Mordren Lore
  - Tashraan Lore
  - Hextus Lore
  - Vandalheim Lore
  terrain:
  - Cave Lore
  - Desert Lore
  - Plains Lore
  - Swamp Lore
  - Winterland Lore
  - Mountains Lore
  - Hills Lore
  - Island Lore
  creature:
  - Demon Lore
  - Devil Lore
  - Vampire Lore

