---
pf2noms:
  noms_per_week: 30
  daily_noms_per_player: 1
  nom_amount: 1
  dmnom_amount: 3
  nom_money: 123
  dmnom_money: 369
  rpp_alt_tiers:
    - 0
    - 100
    - 250
    - 450
    - 700
  permissions:
    dmnom: Give DM noms to players.
