---
skin:
  divider: "%x24------------------------------------------------------------------------------%xn"
  footer: "%x24+=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=+%xn"
  header: "%x24+=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=+%xn"
  line_with_text:
    default:
      color: "%x24"
      pattern: "=--"
      text_position: 6
      left_bracket: "[ "
      right_bracket: " ]"
  plain: "%x24+=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=+%xn"
  random_colors:
  - "%xc"
  - "%xb"
  - "%xg"
  - "%xr"
