---
utils:
  shortcuts:
    colors: color
    ansi: color
    think: echo
    "@@": keepalive
    "@": keepalive
    shortcut/remove: shortcut/delete
    note/remove: note/delete
    note/update: note/add
    die: roll
    notes: note
  permissions:
    manage_notes: Can access admin-only notes.
