---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: name
    width: 20
    title: Name
  - field: ancestry
    width: 18
    title: Ancestry
  - field: charclass
    width: 16
    title: Class
  - field: level
    width: 6
    title: Level
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
