---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: name
    width: 18
    title: Name
  - field: ancestry
    width: 13
    title: Ancestry
  - field: charclass
    width: 13
    title: Class
  - field: tier
    width: 6
    title: Tier
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
